version: '2'
services:
  web:
    image: node:11
    volumes:
      - .:/usr/src/service/
    working_dir: /usr/src/service/

    command: bash -c "chmod +x wait-for-it.sh && npm install -g nodemon && ./wait-for-it.sh elasticsearch:9200 -t 0 --strict && nodemon --exec \"node script.js -d\""
    ports:
     - 1234:1234
     - 1235:1235
     - 3000:3000
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
#    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.1
    environment:
        - cluster.name=docker-cluster
        - bootstrap.memory_lock=true
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.2
    ports:
      - "5601:5601"
